-- Migration 005: Add execution_id to job_executions for deduplication
--
-- The execution_id is a unique identifier generated by the vehicle for each
-- job execution. Without it, duplicate execution records can be inserted when:
-- 1. The vehicle retransmits sync messages (e.g., on reconnect)
-- 2. The vehicle-side sync bridge detects the same terminal transition multiple times
--
-- This migration adds the execution_id column and a unique constraint to prevent duplicates.

-- Add execution_id column (nullable for backward compatibility with existing rows)
-- Note: PostgreSQL < 11 doesn't support IF NOT EXISTS for ADD COLUMN
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'job_executions' AND column_name = 'execution_id'
    ) THEN
        ALTER TABLE job_executions ADD COLUMN execution_id VARCHAR(64);
    END IF;
END $$;

-- Add unique constraint on execution_id (partial index for non-null values)
-- This allows ON CONFLICT (execution_id) DO NOTHING to work correctly
CREATE UNIQUE INDEX IF NOT EXISTS idx_job_executions_execution_id
ON job_executions(execution_id) WHERE execution_id IS NOT NULL;
