# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cloud_dispatcher_service_pb2 as cloud__dispatcher__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cloud_dispatcher_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CloudDispatcherServiceStub(object):
    """=== gRPC Service Definition ===

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CallMethod = channel.unary_unary(
                '/ifex.cloud.dispatcher.CloudDispatcherService/CallMethod',
                request_serializer=cloud__dispatcher__service__pb2.CallMethodRequest.SerializeToString,
                response_deserializer=cloud__dispatcher__service__pb2.CallMethodResponse.FromString,
                _registered_method=True)
        self.CallMethodAsync = channel.unary_unary(
                '/ifex.cloud.dispatcher.CloudDispatcherService/CallMethodAsync',
                request_serializer=cloud__dispatcher__service__pb2.CallMethodAsyncRequest.SerializeToString,
                response_deserializer=cloud__dispatcher__service__pb2.CallMethodAsyncResponse.FromString,
                _registered_method=True)
        self.GetRpcStatus = channel.unary_unary(
                '/ifex.cloud.dispatcher.CloudDispatcherService/GetRpcStatus',
                request_serializer=cloud__dispatcher__service__pb2.GetRpcStatusRequest.SerializeToString,
                response_deserializer=cloud__dispatcher__service__pb2.GetRpcStatusResponse.FromString,
                _registered_method=True)
        self.ListRpcRequests = channel.unary_unary(
                '/ifex.cloud.dispatcher.CloudDispatcherService/ListRpcRequests',
                request_serializer=cloud__dispatcher__service__pb2.ListRpcRequestsRequest.SerializeToString,
                response_deserializer=cloud__dispatcher__service__pb2.ListRpcRequestsResponse.FromString,
                _registered_method=True)
        self.CancelRpc = channel.unary_unary(
                '/ifex.cloud.dispatcher.CloudDispatcherService/CancelRpc',
                request_serializer=cloud__dispatcher__service__pb2.CancelRpcRequest.SerializeToString,
                response_deserializer=cloud__dispatcher__service__pb2.CancelRpcResponse.FromString,
                _registered_method=True)
        self.CallFleetMethod = channel.unary_unary(
                '/ifex.cloud.dispatcher.CloudDispatcherService/CallFleetMethod',
                request_serializer=cloud__dispatcher__service__pb2.CallFleetMethodRequest.SerializeToString,
                response_deserializer=cloud__dispatcher__service__pb2.CallFleetMethodResponse.FromString,
                _registered_method=True)


class CloudDispatcherServiceServicer(object):
    """=== gRPC Service Definition ===

    """

    def CallMethod(self, request, context):
        """Synchronous RPC call (blocks until response or timeout)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallMethodAsync(self, request, context):
        """Asynchronous RPC call (returns correlation_id for polling)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRpcStatus(self, request, context):
        """Get status/result of an RPC request by correlation_id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRpcRequests(self, request, context):
        """List RPC requests for monitoring
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelRpc(self, request, context):
        """Cancel a pending RPC request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallFleetMethod(self, request, context):
        """Invoke method on multiple vehicles
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CloudDispatcherServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CallMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.CallMethod,
                    request_deserializer=cloud__dispatcher__service__pb2.CallMethodRequest.FromString,
                    response_serializer=cloud__dispatcher__service__pb2.CallMethodResponse.SerializeToString,
            ),
            'CallMethodAsync': grpc.unary_unary_rpc_method_handler(
                    servicer.CallMethodAsync,
                    request_deserializer=cloud__dispatcher__service__pb2.CallMethodAsyncRequest.FromString,
                    response_serializer=cloud__dispatcher__service__pb2.CallMethodAsyncResponse.SerializeToString,
            ),
            'GetRpcStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRpcStatus,
                    request_deserializer=cloud__dispatcher__service__pb2.GetRpcStatusRequest.FromString,
                    response_serializer=cloud__dispatcher__service__pb2.GetRpcStatusResponse.SerializeToString,
            ),
            'ListRpcRequests': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRpcRequests,
                    request_deserializer=cloud__dispatcher__service__pb2.ListRpcRequestsRequest.FromString,
                    response_serializer=cloud__dispatcher__service__pb2.ListRpcRequestsResponse.SerializeToString,
            ),
            'CancelRpc': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelRpc,
                    request_deserializer=cloud__dispatcher__service__pb2.CancelRpcRequest.FromString,
                    response_serializer=cloud__dispatcher__service__pb2.CancelRpcResponse.SerializeToString,
            ),
            'CallFleetMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.CallFleetMethod,
                    request_deserializer=cloud__dispatcher__service__pb2.CallFleetMethodRequest.FromString,
                    response_serializer=cloud__dispatcher__service__pb2.CallFleetMethodResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ifex.cloud.dispatcher.CloudDispatcherService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ifex.cloud.dispatcher.CloudDispatcherService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CloudDispatcherService(object):
    """=== gRPC Service Definition ===

    """

    @staticmethod
    def CallMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ifex.cloud.dispatcher.CloudDispatcherService/CallMethod',
            cloud__dispatcher__service__pb2.CallMethodRequest.SerializeToString,
            cloud__dispatcher__service__pb2.CallMethodResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallMethodAsync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ifex.cloud.dispatcher.CloudDispatcherService/CallMethodAsync',
            cloud__dispatcher__service__pb2.CallMethodAsyncRequest.SerializeToString,
            cloud__dispatcher__service__pb2.CallMethodAsyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRpcStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ifex.cloud.dispatcher.CloudDispatcherService/GetRpcStatus',
            cloud__dispatcher__service__pb2.GetRpcStatusRequest.SerializeToString,
            cloud__dispatcher__service__pb2.GetRpcStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRpcRequests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ifex.cloud.dispatcher.CloudDispatcherService/ListRpcRequests',
            cloud__dispatcher__service__pb2.ListRpcRequestsRequest.SerializeToString,
            cloud__dispatcher__service__pb2.ListRpcRequestsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelRpc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ifex.cloud.dispatcher.CloudDispatcherService/CancelRpc',
            cloud__dispatcher__service__pb2.CancelRpcRequest.SerializeToString,
            cloud__dispatcher__service__pb2.CancelRpcResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallFleetMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ifex.cloud.dispatcher.CloudDispatcherService/CallFleetMethod',
            cloud__dispatcher__service__pb2.CallFleetMethodRequest.SerializeToString,
            cloud__dispatcher__service__pb2.CallFleetMethodResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
