# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cloud_scheduler_service_pb2 as cloud__scheduler__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cloud_scheduler_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CloudSchedulerServiceStub(object):
    """=== gRPC Service Definition ===

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateJob = channel.unary_unary(
                '/ifex.cloud.scheduler.CloudSchedulerService/CreateJob',
                request_serializer=cloud__scheduler__service__pb2.CreateJobRequest.SerializeToString,
                response_deserializer=cloud__scheduler__service__pb2.CreateJobResponse.FromString,
                _registered_method=True)
        self.UpdateJob = channel.unary_unary(
                '/ifex.cloud.scheduler.CloudSchedulerService/UpdateJob',
                request_serializer=cloud__scheduler__service__pb2.UpdateJobRequest.SerializeToString,
                response_deserializer=cloud__scheduler__service__pb2.UpdateJobResponse.FromString,
                _registered_method=True)
        self.DeleteJob = channel.unary_unary(
                '/ifex.cloud.scheduler.CloudSchedulerService/DeleteJob',
                request_serializer=cloud__scheduler__service__pb2.DeleteJobRequest.SerializeToString,
                response_deserializer=cloud__scheduler__service__pb2.DeleteJobResponse.FromString,
                _registered_method=True)
        self.PauseJob = channel.unary_unary(
                '/ifex.cloud.scheduler.CloudSchedulerService/PauseJob',
                request_serializer=cloud__scheduler__service__pb2.PauseJobRequest.SerializeToString,
                response_deserializer=cloud__scheduler__service__pb2.PauseJobResponse.FromString,
                _registered_method=True)
        self.ResumeJob = channel.unary_unary(
                '/ifex.cloud.scheduler.CloudSchedulerService/ResumeJob',
                request_serializer=cloud__scheduler__service__pb2.ResumeJobRequest.SerializeToString,
                response_deserializer=cloud__scheduler__service__pb2.ResumeJobResponse.FromString,
                _registered_method=True)
        self.TriggerJob = channel.unary_unary(
                '/ifex.cloud.scheduler.CloudSchedulerService/TriggerJob',
                request_serializer=cloud__scheduler__service__pb2.TriggerJobRequest.SerializeToString,
                response_deserializer=cloud__scheduler__service__pb2.TriggerJobResponse.FromString,
                _registered_method=True)
        self.GetJob = channel.unary_unary(
                '/ifex.cloud.scheduler.CloudSchedulerService/GetJob',
                request_serializer=cloud__scheduler__service__pb2.GetJobRequest.SerializeToString,
                response_deserializer=cloud__scheduler__service__pb2.GetJobResponse.FromString,
                _registered_method=True)
        self.ListJobs = channel.unary_unary(
                '/ifex.cloud.scheduler.CloudSchedulerService/ListJobs',
                request_serializer=cloud__scheduler__service__pb2.ListJobsRequest.SerializeToString,
                response_deserializer=cloud__scheduler__service__pb2.ListJobsResponse.FromString,
                _registered_method=True)
        self.GetJobExecutions = channel.unary_unary(
                '/ifex.cloud.scheduler.CloudSchedulerService/GetJobExecutions',
                request_serializer=cloud__scheduler__service__pb2.GetJobExecutionsRequest.SerializeToString,
                response_deserializer=cloud__scheduler__service__pb2.GetJobExecutionsResponse.FromString,
                _registered_method=True)
        self.CreateFleetJob = channel.unary_unary(
                '/ifex.cloud.scheduler.CloudSchedulerService/CreateFleetJob',
                request_serializer=cloud__scheduler__service__pb2.CreateFleetJobRequest.SerializeToString,
                response_deserializer=cloud__scheduler__service__pb2.CreateFleetJobResponse.FromString,
                _registered_method=True)
        self.DeleteFleetJob = channel.unary_unary(
                '/ifex.cloud.scheduler.CloudSchedulerService/DeleteFleetJob',
                request_serializer=cloud__scheduler__service__pb2.DeleteFleetJobRequest.SerializeToString,
                response_deserializer=cloud__scheduler__service__pb2.DeleteFleetJobResponse.FromString,
                _registered_method=True)
        self.GetFleetJobStats = channel.unary_unary(
                '/ifex.cloud.scheduler.CloudSchedulerService/GetFleetJobStats',
                request_serializer=cloud__scheduler__service__pb2.GetFleetJobStatsRequest.SerializeToString,
                response_deserializer=cloud__scheduler__service__pb2.GetFleetJobStatsResponse.FromString,
                _registered_method=True)


class CloudSchedulerServiceServicer(object):
    """=== gRPC Service Definition ===

    """

    def CreateJob(self, request, context):
        """Single vehicle operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJob(self, request, context):
        """Query operations (read from PostgreSQL)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobExecutions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateFleetJob(self, request, context):
        """Fleet-wide operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFleetJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFleetJobStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CloudSchedulerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateJob,
                    request_deserializer=cloud__scheduler__service__pb2.CreateJobRequest.FromString,
                    response_serializer=cloud__scheduler__service__pb2.CreateJobResponse.SerializeToString,
            ),
            'UpdateJob': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateJob,
                    request_deserializer=cloud__scheduler__service__pb2.UpdateJobRequest.FromString,
                    response_serializer=cloud__scheduler__service__pb2.UpdateJobResponse.SerializeToString,
            ),
            'DeleteJob': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteJob,
                    request_deserializer=cloud__scheduler__service__pb2.DeleteJobRequest.FromString,
                    response_serializer=cloud__scheduler__service__pb2.DeleteJobResponse.SerializeToString,
            ),
            'PauseJob': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseJob,
                    request_deserializer=cloud__scheduler__service__pb2.PauseJobRequest.FromString,
                    response_serializer=cloud__scheduler__service__pb2.PauseJobResponse.SerializeToString,
            ),
            'ResumeJob': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeJob,
                    request_deserializer=cloud__scheduler__service__pb2.ResumeJobRequest.FromString,
                    response_serializer=cloud__scheduler__service__pb2.ResumeJobResponse.SerializeToString,
            ),
            'TriggerJob': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerJob,
                    request_deserializer=cloud__scheduler__service__pb2.TriggerJobRequest.FromString,
                    response_serializer=cloud__scheduler__service__pb2.TriggerJobResponse.SerializeToString,
            ),
            'GetJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJob,
                    request_deserializer=cloud__scheduler__service__pb2.GetJobRequest.FromString,
                    response_serializer=cloud__scheduler__service__pb2.GetJobResponse.SerializeToString,
            ),
            'ListJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListJobs,
                    request_deserializer=cloud__scheduler__service__pb2.ListJobsRequest.FromString,
                    response_serializer=cloud__scheduler__service__pb2.ListJobsResponse.SerializeToString,
            ),
            'GetJobExecutions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobExecutions,
                    request_deserializer=cloud__scheduler__service__pb2.GetJobExecutionsRequest.FromString,
                    response_serializer=cloud__scheduler__service__pb2.GetJobExecutionsResponse.SerializeToString,
            ),
            'CreateFleetJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFleetJob,
                    request_deserializer=cloud__scheduler__service__pb2.CreateFleetJobRequest.FromString,
                    response_serializer=cloud__scheduler__service__pb2.CreateFleetJobResponse.SerializeToString,
            ),
            'DeleteFleetJob': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFleetJob,
                    request_deserializer=cloud__scheduler__service__pb2.DeleteFleetJobRequest.FromString,
                    response_serializer=cloud__scheduler__service__pb2.DeleteFleetJobResponse.SerializeToString,
            ),
            'GetFleetJobStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFleetJobStats,
                    request_deserializer=cloud__scheduler__service__pb2.GetFleetJobStatsRequest.FromString,
                    response_serializer=cloud__scheduler__service__pb2.GetFleetJobStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ifex.cloud.scheduler.CloudSchedulerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ifex.cloud.scheduler.CloudSchedulerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CloudSchedulerService(object):
    """=== gRPC Service Definition ===

    """

    @staticmethod
    def CreateJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ifex.cloud.scheduler.CloudSchedulerService/CreateJob',
            cloud__scheduler__service__pb2.CreateJobRequest.SerializeToString,
            cloud__scheduler__service__pb2.CreateJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ifex.cloud.scheduler.CloudSchedulerService/UpdateJob',
            cloud__scheduler__service__pb2.UpdateJobRequest.SerializeToString,
            cloud__scheduler__service__pb2.UpdateJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ifex.cloud.scheduler.CloudSchedulerService/DeleteJob',
            cloud__scheduler__service__pb2.DeleteJobRequest.SerializeToString,
            cloud__scheduler__service__pb2.DeleteJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ifex.cloud.scheduler.CloudSchedulerService/PauseJob',
            cloud__scheduler__service__pb2.PauseJobRequest.SerializeToString,
            cloud__scheduler__service__pb2.PauseJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ifex.cloud.scheduler.CloudSchedulerService/ResumeJob',
            cloud__scheduler__service__pb2.ResumeJobRequest.SerializeToString,
            cloud__scheduler__service__pb2.ResumeJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ifex.cloud.scheduler.CloudSchedulerService/TriggerJob',
            cloud__scheduler__service__pb2.TriggerJobRequest.SerializeToString,
            cloud__scheduler__service__pb2.TriggerJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ifex.cloud.scheduler.CloudSchedulerService/GetJob',
            cloud__scheduler__service__pb2.GetJobRequest.SerializeToString,
            cloud__scheduler__service__pb2.GetJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ifex.cloud.scheduler.CloudSchedulerService/ListJobs',
            cloud__scheduler__service__pb2.ListJobsRequest.SerializeToString,
            cloud__scheduler__service__pb2.ListJobsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobExecutions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ifex.cloud.scheduler.CloudSchedulerService/GetJobExecutions',
            cloud__scheduler__service__pb2.GetJobExecutionsRequest.SerializeToString,
            cloud__scheduler__service__pb2.GetJobExecutionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateFleetJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ifex.cloud.scheduler.CloudSchedulerService/CreateFleetJob',
            cloud__scheduler__service__pb2.CreateFleetJobRequest.SerializeToString,
            cloud__scheduler__service__pb2.CreateFleetJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFleetJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ifex.cloud.scheduler.CloudSchedulerService/DeleteFleetJob',
            cloud__scheduler__service__pb2.DeleteFleetJobRequest.SerializeToString,
            cloud__scheduler__service__pb2.DeleteFleetJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFleetJobStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ifex.cloud.scheduler.CloudSchedulerService/GetFleetJobStats',
            cloud__scheduler__service__pb2.GetFleetJobStatsRequest.SerializeToString,
            cloud__scheduler__service__pb2.GetFleetJobStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
