# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import cloud_backend_transport_service_pb2 as cloud__backend__transport__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cloud_backend_transport_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class send_to_vehicle_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.send_to_vehicle = channel.unary_unary(
                '/swdv.cloud_backend_transport_service.send_to_vehicle_service/send_to_vehicle',
                request_serializer=cloud__backend__transport__service__pb2.send_to_vehicle_request.SerializeToString,
                response_deserializer=cloud__backend__transport__service__pb2.send_to_vehicle_response.FromString,
                _registered_method=True)


class send_to_vehicle_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def send_to_vehicle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_send_to_vehicle_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'send_to_vehicle': grpc.unary_unary_rpc_method_handler(
                    servicer.send_to_vehicle,
                    request_deserializer=cloud__backend__transport__service__pb2.send_to_vehicle_request.FromString,
                    response_serializer=cloud__backend__transport__service__pb2.send_to_vehicle_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_backend_transport_service.send_to_vehicle_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swdv.cloud_backend_transport_service.send_to_vehicle_service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class send_to_vehicle_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def send_to_vehicle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swdv.cloud_backend_transport_service.send_to_vehicle_service/send_to_vehicle',
            cloud__backend__transport__service__pb2.send_to_vehicle_request.SerializeToString,
            cloud__backend__transport__service__pb2.send_to_vehicle_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class get_vehicle_status_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_vehicle_status = channel.unary_unary(
                '/swdv.cloud_backend_transport_service.get_vehicle_status_service/get_vehicle_status',
                request_serializer=cloud__backend__transport__service__pb2.get_vehicle_status_request.SerializeToString,
                response_deserializer=cloud__backend__transport__service__pb2.get_vehicle_status_response.FromString,
                _registered_method=True)


class get_vehicle_status_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_vehicle_status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_get_vehicle_status_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_vehicle_status': grpc.unary_unary_rpc_method_handler(
                    servicer.get_vehicle_status,
                    request_deserializer=cloud__backend__transport__service__pb2.get_vehicle_status_request.FromString,
                    response_serializer=cloud__backend__transport__service__pb2.get_vehicle_status_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_backend_transport_service.get_vehicle_status_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swdv.cloud_backend_transport_service.get_vehicle_status_service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class get_vehicle_status_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_vehicle_status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swdv.cloud_backend_transport_service.get_vehicle_status_service/get_vehicle_status',
            cloud__backend__transport__service__pb2.get_vehicle_status_request.SerializeToString,
            cloud__backend__transport__service__pb2.get_vehicle_status_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class get_channel_info_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_channel_info = channel.unary_unary(
                '/swdv.cloud_backend_transport_service.get_channel_info_service/get_channel_info',
                request_serializer=cloud__backend__transport__service__pb2.get_channel_info_request.SerializeToString,
                response_deserializer=cloud__backend__transport__service__pb2.get_channel_info_response.FromString,
                _registered_method=True)


class get_channel_info_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_channel_info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_get_channel_info_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_channel_info': grpc.unary_unary_rpc_method_handler(
                    servicer.get_channel_info,
                    request_deserializer=cloud__backend__transport__service__pb2.get_channel_info_request.FromString,
                    response_serializer=cloud__backend__transport__service__pb2.get_channel_info_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_backend_transport_service.get_channel_info_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swdv.cloud_backend_transport_service.get_channel_info_service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class get_channel_info_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_channel_info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swdv.cloud_backend_transport_service.get_channel_info_service/get_channel_info',
            cloud__backend__transport__service__pb2.get_channel_info_request.SerializeToString,
            cloud__backend__transport__service__pb2.get_channel_info_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class get_queue_status_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_queue_status = channel.unary_unary(
                '/swdv.cloud_backend_transport_service.get_queue_status_service/get_queue_status',
                request_serializer=cloud__backend__transport__service__pb2.get_queue_status_request.SerializeToString,
                response_deserializer=cloud__backend__transport__service__pb2.get_queue_status_response.FromString,
                _registered_method=True)


class get_queue_status_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_queue_status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_get_queue_status_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_queue_status': grpc.unary_unary_rpc_method_handler(
                    servicer.get_queue_status,
                    request_deserializer=cloud__backend__transport__service__pb2.get_queue_status_request.FromString,
                    response_serializer=cloud__backend__transport__service__pb2.get_queue_status_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_backend_transport_service.get_queue_status_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swdv.cloud_backend_transport_service.get_queue_status_service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class get_queue_status_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_queue_status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swdv.cloud_backend_transport_service.get_queue_status_service/get_queue_status',
            cloud__backend__transport__service__pb2.get_queue_status_request.SerializeToString,
            cloud__backend__transport__service__pb2.get_queue_status_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class get_stats_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_stats = channel.unary_unary(
                '/swdv.cloud_backend_transport_service.get_stats_service/get_stats',
                request_serializer=cloud__backend__transport__service__pb2.get_stats_request.SerializeToString,
                response_deserializer=cloud__backend__transport__service__pb2.get_stats_response.FromString,
                _registered_method=True)


class get_stats_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_stats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_get_stats_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_stats': grpc.unary_unary_rpc_method_handler(
                    servicer.get_stats,
                    request_deserializer=cloud__backend__transport__service__pb2.get_stats_request.FromString,
                    response_serializer=cloud__backend__transport__service__pb2.get_stats_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_backend_transport_service.get_stats_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swdv.cloud_backend_transport_service.get_stats_service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class get_stats_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_stats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swdv.cloud_backend_transport_service.get_stats_service/get_stats',
            cloud__backend__transport__service__pb2.get_stats_request.SerializeToString,
            cloud__backend__transport__service__pb2.get_stats_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class healthy_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.healthy = channel.unary_unary(
                '/swdv.cloud_backend_transport_service.healthy_service/healthy',
                request_serializer=cloud__backend__transport__service__pb2.healthy_request.SerializeToString,
                response_deserializer=cloud__backend__transport__service__pb2.healthy_response.FromString,
                _registered_method=True)


class healthy_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def healthy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_healthy_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'healthy': grpc.unary_unary_rpc_method_handler(
                    servicer.healthy,
                    request_deserializer=cloud__backend__transport__service__pb2.healthy_request.FromString,
                    response_serializer=cloud__backend__transport__service__pb2.healthy_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_backend_transport_service.healthy_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swdv.cloud_backend_transport_service.healthy_service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class healthy_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def healthy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swdv.cloud_backend_transport_service.healthy_service/healthy',
            cloud__backend__transport__service__pb2.healthy_request.SerializeToString,
            cloud__backend__transport__service__pb2.healthy_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class on_vehicle_message_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.subscribe = channel.unary_stream(
                '/swdv.cloud_backend_transport_service.on_vehicle_message_service/subscribe',
                request_serializer=cloud__backend__transport__service__pb2.on_vehicle_message_subscribe_request.SerializeToString,
                response_deserializer=cloud__backend__transport__service__pb2.on_vehicle_message.FromString,
                _registered_method=True)


class on_vehicle_message_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def subscribe(self, request, context):
        """Server-streaming RPC for event subscription
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_on_vehicle_message_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.subscribe,
                    request_deserializer=cloud__backend__transport__service__pb2.on_vehicle_message_subscribe_request.FromString,
                    response_serializer=cloud__backend__transport__service__pb2.on_vehicle_message.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_backend_transport_service.on_vehicle_message_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swdv.cloud_backend_transport_service.on_vehicle_message_service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class on_vehicle_message_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/swdv.cloud_backend_transport_service.on_vehicle_message_service/subscribe',
            cloud__backend__transport__service__pb2.on_vehicle_message_subscribe_request.SerializeToString,
            cloud__backend__transport__service__pb2.on_vehicle_message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class on_ack_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.subscribe = channel.unary_stream(
                '/swdv.cloud_backend_transport_service.on_ack_service/subscribe',
                request_serializer=cloud__backend__transport__service__pb2.on_ack_subscribe_request.SerializeToString,
                response_deserializer=cloud__backend__transport__service__pb2.on_ack.FromString,
                _registered_method=True)


class on_ack_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def subscribe(self, request, context):
        """Server-streaming RPC for event subscription
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_on_ack_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.subscribe,
                    request_deserializer=cloud__backend__transport__service__pb2.on_ack_subscribe_request.FromString,
                    response_serializer=cloud__backend__transport__service__pb2.on_ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_backend_transport_service.on_ack_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swdv.cloud_backend_transport_service.on_ack_service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class on_ack_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/swdv.cloud_backend_transport_service.on_ack_service/subscribe',
            cloud__backend__transport__service__pb2.on_ack_subscribe_request.SerializeToString,
            cloud__backend__transport__service__pb2.on_ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class on_vehicle_status_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.subscribe = channel.unary_stream(
                '/swdv.cloud_backend_transport_service.on_vehicle_status_service/subscribe',
                request_serializer=cloud__backend__transport__service__pb2.on_vehicle_status_subscribe_request.SerializeToString,
                response_deserializer=cloud__backend__transport__service__pb2.on_vehicle_status.FromString,
                _registered_method=True)


class on_vehicle_status_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def subscribe(self, request, context):
        """Server-streaming RPC for event subscription
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_on_vehicle_status_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.subscribe,
                    request_deserializer=cloud__backend__transport__service__pb2.on_vehicle_status_subscribe_request.FromString,
                    response_serializer=cloud__backend__transport__service__pb2.on_vehicle_status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_backend_transport_service.on_vehicle_status_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swdv.cloud_backend_transport_service.on_vehicle_status_service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class on_vehicle_status_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/swdv.cloud_backend_transport_service.on_vehicle_status_service/subscribe',
            cloud__backend__transport__service__pb2.on_vehicle_status_subscribe_request.SerializeToString,
            cloud__backend__transport__service__pb2.on_vehicle_status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class on_queue_status_changed_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.subscribe = channel.unary_stream(
                '/swdv.cloud_backend_transport_service.on_queue_status_changed_service/subscribe',
                request_serializer=cloud__backend__transport__service__pb2.on_queue_status_changed_subscribe_request.SerializeToString,
                response_deserializer=cloud__backend__transport__service__pb2.on_queue_status_changed.FromString,
                _registered_method=True)


class on_queue_status_changed_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def subscribe(self, request, context):
        """Server-streaming RPC for event subscription
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_on_queue_status_changed_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.subscribe,
                    request_deserializer=cloud__backend__transport__service__pb2.on_queue_status_changed_subscribe_request.FromString,
                    response_serializer=cloud__backend__transport__service__pb2.on_queue_status_changed.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_backend_transport_service.on_queue_status_changed_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swdv.cloud_backend_transport_service.on_queue_status_changed_service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class on_queue_status_changed_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/swdv.cloud_backend_transport_service.on_queue_status_changed_service/subscribe',
            cloud__backend__transport__service__pb2.on_queue_status_changed_subscribe_request.SerializeToString,
            cloud__backend__transport__service__pb2.on_queue_status_changed.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
