# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import cloud_discovery_service_pb2 as cloud__discovery__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cloud_discovery_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class list_vehicles_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.list_vehicles = channel.unary_unary(
                '/swdv.cloud_discovery_service.list_vehicles_service/list_vehicles',
                request_serializer=cloud__discovery__service__pb2.list_vehicles_request.SerializeToString,
                response_deserializer=cloud__discovery__service__pb2.list_vehicles_response.FromString,
                _registered_method=True)


class list_vehicles_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def list_vehicles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_list_vehicles_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'list_vehicles': grpc.unary_unary_rpc_method_handler(
                    servicer.list_vehicles,
                    request_deserializer=cloud__discovery__service__pb2.list_vehicles_request.FromString,
                    response_serializer=cloud__discovery__service__pb2.list_vehicles_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_discovery_service.list_vehicles_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swdv.cloud_discovery_service.list_vehicles_service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class list_vehicles_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def list_vehicles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swdv.cloud_discovery_service.list_vehicles_service/list_vehicles',
            cloud__discovery__service__pb2.list_vehicles_request.SerializeToString,
            cloud__discovery__service__pb2.list_vehicles_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class get_vehicle_services_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_vehicle_services = channel.unary_unary(
                '/swdv.cloud_discovery_service.get_vehicle_services_service/get_vehicle_services',
                request_serializer=cloud__discovery__service__pb2.get_vehicle_services_request.SerializeToString,
                response_deserializer=cloud__discovery__service__pb2.get_vehicle_services_response.FromString,
                _registered_method=True)


class get_vehicle_services_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_vehicle_services(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_get_vehicle_services_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_vehicle_services': grpc.unary_unary_rpc_method_handler(
                    servicer.get_vehicle_services,
                    request_deserializer=cloud__discovery__service__pb2.get_vehicle_services_request.FromString,
                    response_serializer=cloud__discovery__service__pb2.get_vehicle_services_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_discovery_service.get_vehicle_services_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swdv.cloud_discovery_service.get_vehicle_services_service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class get_vehicle_services_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_vehicle_services(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swdv.cloud_discovery_service.get_vehicle_services_service/get_vehicle_services',
            cloud__discovery__service__pb2.get_vehicle_services_request.SerializeToString,
            cloud__discovery__service__pb2.get_vehicle_services_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class query_services_by_name_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.query_services_by_name = channel.unary_unary(
                '/swdv.cloud_discovery_service.query_services_by_name_service/query_services_by_name',
                request_serializer=cloud__discovery__service__pb2.query_services_by_name_request.SerializeToString,
                response_deserializer=cloud__discovery__service__pb2.query_services_by_name_response.FromString,
                _registered_method=True)


class query_services_by_name_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def query_services_by_name(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_query_services_by_name_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'query_services_by_name': grpc.unary_unary_rpc_method_handler(
                    servicer.query_services_by_name,
                    request_deserializer=cloud__discovery__service__pb2.query_services_by_name_request.FromString,
                    response_serializer=cloud__discovery__service__pb2.query_services_by_name_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_discovery_service.query_services_by_name_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swdv.cloud_discovery_service.query_services_by_name_service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class query_services_by_name_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def query_services_by_name(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swdv.cloud_discovery_service.query_services_by_name_service/query_services_by_name',
            cloud__discovery__service__pb2.query_services_by_name_request.SerializeToString,
            cloud__discovery__service__pb2.query_services_by_name_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class get_fleet_service_stats_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_fleet_service_stats = channel.unary_unary(
                '/swdv.cloud_discovery_service.get_fleet_service_stats_service/get_fleet_service_stats',
                request_serializer=cloud__discovery__service__pb2.get_fleet_service_stats_request.SerializeToString,
                response_deserializer=cloud__discovery__service__pb2.get_fleet_service_stats_response.FromString,
                _registered_method=True)


class get_fleet_service_stats_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_fleet_service_stats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_get_fleet_service_stats_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_fleet_service_stats': grpc.unary_unary_rpc_method_handler(
                    servicer.get_fleet_service_stats,
                    request_deserializer=cloud__discovery__service__pb2.get_fleet_service_stats_request.FromString,
                    response_serializer=cloud__discovery__service__pb2.get_fleet_service_stats_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_discovery_service.get_fleet_service_stats_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swdv.cloud_discovery_service.get_fleet_service_stats_service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class get_fleet_service_stats_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_fleet_service_stats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swdv.cloud_discovery_service.get_fleet_service_stats_service/get_fleet_service_stats',
            cloud__discovery__service__pb2.get_fleet_service_stats_request.SerializeToString,
            cloud__discovery__service__pb2.get_fleet_service_stats_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class find_vehicles_with_service_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.find_vehicles_with_service = channel.unary_unary(
                '/swdv.cloud_discovery_service.find_vehicles_with_service_service/find_vehicles_with_service',
                request_serializer=cloud__discovery__service__pb2.find_vehicles_with_service_request.SerializeToString,
                response_deserializer=cloud__discovery__service__pb2.find_vehicles_with_service_response.FromString,
                _registered_method=True)


class find_vehicles_with_service_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def find_vehicles_with_service(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_find_vehicles_with_service_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'find_vehicles_with_service': grpc.unary_unary_rpc_method_handler(
                    servicer.find_vehicles_with_service,
                    request_deserializer=cloud__discovery__service__pb2.find_vehicles_with_service_request.FromString,
                    response_serializer=cloud__discovery__service__pb2.find_vehicles_with_service_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_discovery_service.find_vehicles_with_service_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swdv.cloud_discovery_service.find_vehicles_with_service_service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class find_vehicles_with_service_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def find_vehicles_with_service(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swdv.cloud_discovery_service.find_vehicles_with_service_service/find_vehicles_with_service',
            cloud__discovery__service__pb2.find_vehicles_with_service_request.SerializeToString,
            cloud__discovery__service__pb2.find_vehicles_with_service_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class healthy_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.healthy = channel.unary_unary(
                '/swdv.cloud_discovery_service.healthy_service/healthy',
                request_serializer=cloud__discovery__service__pb2.healthy_request.SerializeToString,
                response_deserializer=cloud__discovery__service__pb2.healthy_response.FromString,
                _registered_method=True)


class healthy_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def healthy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_healthy_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'healthy': grpc.unary_unary_rpc_method_handler(
                    servicer.healthy,
                    request_deserializer=cloud__discovery__service__pb2.healthy_request.FromString,
                    response_serializer=cloud__discovery__service__pb2.healthy_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_discovery_service.healthy_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swdv.cloud_discovery_service.healthy_service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class healthy_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def healthy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swdv.cloud_discovery_service.healthy_service/healthy',
            cloud__discovery__service__pb2.healthy_request.SerializeToString,
            cloud__discovery__service__pb2.healthy_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
