# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import cloud_dispatcher_service_pb2 as cloud__dispatcher__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cloud_dispatcher_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class call_method_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.call_method = channel.unary_unary(
                '/swdv.cloud_dispatcher_service.call_method_service/call_method',
                request_serializer=cloud__dispatcher__service__pb2.call_method_request.SerializeToString,
                response_deserializer=cloud__dispatcher__service__pb2.call_method_response.FromString,
                _registered_method=True)


class call_method_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def call_method(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_call_method_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'call_method': grpc.unary_unary_rpc_method_handler(
                    servicer.call_method,
                    request_deserializer=cloud__dispatcher__service__pb2.call_method_request.FromString,
                    response_serializer=cloud__dispatcher__service__pb2.call_method_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_dispatcher_service.call_method_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swdv.cloud_dispatcher_service.call_method_service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class call_method_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def call_method(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swdv.cloud_dispatcher_service.call_method_service/call_method',
            cloud__dispatcher__service__pb2.call_method_request.SerializeToString,
            cloud__dispatcher__service__pb2.call_method_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class call_method_async_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.call_method_async = channel.unary_unary(
                '/swdv.cloud_dispatcher_service.call_method_async_service/call_method_async',
                request_serializer=cloud__dispatcher__service__pb2.call_method_async_request.SerializeToString,
                response_deserializer=cloud__dispatcher__service__pb2.call_method_async_response.FromString,
                _registered_method=True)


class call_method_async_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def call_method_async(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_call_method_async_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'call_method_async': grpc.unary_unary_rpc_method_handler(
                    servicer.call_method_async,
                    request_deserializer=cloud__dispatcher__service__pb2.call_method_async_request.FromString,
                    response_serializer=cloud__dispatcher__service__pb2.call_method_async_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_dispatcher_service.call_method_async_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swdv.cloud_dispatcher_service.call_method_async_service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class call_method_async_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def call_method_async(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swdv.cloud_dispatcher_service.call_method_async_service/call_method_async',
            cloud__dispatcher__service__pb2.call_method_async_request.SerializeToString,
            cloud__dispatcher__service__pb2.call_method_async_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class get_rpc_status_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_rpc_status = channel.unary_unary(
                '/swdv.cloud_dispatcher_service.get_rpc_status_service/get_rpc_status',
                request_serializer=cloud__dispatcher__service__pb2.get_rpc_status_request.SerializeToString,
                response_deserializer=cloud__dispatcher__service__pb2.get_rpc_status_response.FromString,
                _registered_method=True)


class get_rpc_status_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_rpc_status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_get_rpc_status_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_rpc_status': grpc.unary_unary_rpc_method_handler(
                    servicer.get_rpc_status,
                    request_deserializer=cloud__dispatcher__service__pb2.get_rpc_status_request.FromString,
                    response_serializer=cloud__dispatcher__service__pb2.get_rpc_status_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_dispatcher_service.get_rpc_status_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swdv.cloud_dispatcher_service.get_rpc_status_service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class get_rpc_status_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_rpc_status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swdv.cloud_dispatcher_service.get_rpc_status_service/get_rpc_status',
            cloud__dispatcher__service__pb2.get_rpc_status_request.SerializeToString,
            cloud__dispatcher__service__pb2.get_rpc_status_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class list_rpc_requests_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.list_rpc_requests = channel.unary_unary(
                '/swdv.cloud_dispatcher_service.list_rpc_requests_service/list_rpc_requests',
                request_serializer=cloud__dispatcher__service__pb2.list_rpc_requests_request.SerializeToString,
                response_deserializer=cloud__dispatcher__service__pb2.list_rpc_requests_response.FromString,
                _registered_method=True)


class list_rpc_requests_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def list_rpc_requests(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_list_rpc_requests_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'list_rpc_requests': grpc.unary_unary_rpc_method_handler(
                    servicer.list_rpc_requests,
                    request_deserializer=cloud__dispatcher__service__pb2.list_rpc_requests_request.FromString,
                    response_serializer=cloud__dispatcher__service__pb2.list_rpc_requests_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_dispatcher_service.list_rpc_requests_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swdv.cloud_dispatcher_service.list_rpc_requests_service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class list_rpc_requests_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def list_rpc_requests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swdv.cloud_dispatcher_service.list_rpc_requests_service/list_rpc_requests',
            cloud__dispatcher__service__pb2.list_rpc_requests_request.SerializeToString,
            cloud__dispatcher__service__pb2.list_rpc_requests_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class cancel_rpc_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.cancel_rpc = channel.unary_unary(
                '/swdv.cloud_dispatcher_service.cancel_rpc_service/cancel_rpc',
                request_serializer=cloud__dispatcher__service__pb2.cancel_rpc_request.SerializeToString,
                response_deserializer=cloud__dispatcher__service__pb2.cancel_rpc_response.FromString,
                _registered_method=True)


class cancel_rpc_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def cancel_rpc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_cancel_rpc_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'cancel_rpc': grpc.unary_unary_rpc_method_handler(
                    servicer.cancel_rpc,
                    request_deserializer=cloud__dispatcher__service__pb2.cancel_rpc_request.FromString,
                    response_serializer=cloud__dispatcher__service__pb2.cancel_rpc_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_dispatcher_service.cancel_rpc_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swdv.cloud_dispatcher_service.cancel_rpc_service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class cancel_rpc_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def cancel_rpc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swdv.cloud_dispatcher_service.cancel_rpc_service/cancel_rpc',
            cloud__dispatcher__service__pb2.cancel_rpc_request.SerializeToString,
            cloud__dispatcher__service__pb2.cancel_rpc_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class call_fleet_method_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.call_fleet_method = channel.unary_unary(
                '/swdv.cloud_dispatcher_service.call_fleet_method_service/call_fleet_method',
                request_serializer=cloud__dispatcher__service__pb2.call_fleet_method_request.SerializeToString,
                response_deserializer=cloud__dispatcher__service__pb2.call_fleet_method_response.FromString,
                _registered_method=True)


class call_fleet_method_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def call_fleet_method(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_call_fleet_method_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'call_fleet_method': grpc.unary_unary_rpc_method_handler(
                    servicer.call_fleet_method,
                    request_deserializer=cloud__dispatcher__service__pb2.call_fleet_method_request.FromString,
                    response_serializer=cloud__dispatcher__service__pb2.call_fleet_method_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_dispatcher_service.call_fleet_method_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swdv.cloud_dispatcher_service.call_fleet_method_service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class call_fleet_method_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def call_fleet_method(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swdv.cloud_dispatcher_service.call_fleet_method_service/call_fleet_method',
            cloud__dispatcher__service__pb2.call_fleet_method_request.SerializeToString,
            cloud__dispatcher__service__pb2.call_fleet_method_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class healthy_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.healthy = channel.unary_unary(
                '/swdv.cloud_dispatcher_service.healthy_service/healthy',
                request_serializer=cloud__dispatcher__service__pb2.healthy_request.SerializeToString,
                response_deserializer=cloud__dispatcher__service__pb2.healthy_response.FromString,
                _registered_method=True)


class healthy_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def healthy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_healthy_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'healthy': grpc.unary_unary_rpc_method_handler(
                    servicer.healthy,
                    request_deserializer=cloud__dispatcher__service__pb2.healthy_request.FromString,
                    response_serializer=cloud__dispatcher__service__pb2.healthy_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_dispatcher_service.healthy_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('swdv.cloud_dispatcher_service.healthy_service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class healthy_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def healthy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/swdv.cloud_dispatcher_service.healthy_service/healthy',
            cloud__dispatcher__service__pb2.healthy_request.SerializeToString,
            cloud__dispatcher__service__pb2.healthy_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
