# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dispatcher-rpc-envelope.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'dispatcher-rpc-envelope.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x64ispatcher-rpc-envelope.proto\x12\x1cswdv.dispatcher_rpc_envelope\"\x9d\x01\n\rrpc_request_t\x12\x16\n\x0e\x63orrelation_id\x18\x01 \x01(\t\x12\x14\n\x0cservice_name\x18\x02 \x01(\t\x12\x13\n\x0bmethod_name\x18\x03 \x01(\t\x12\x17\n\x0fparameters_json\x18\x04 \x01(\t\x12\x12\n\ntimeout_ms\x18\x05 \x01(\r\x12\x1c\n\x14request_timestamp_ms\x18\x06 \x01(\x12\"\xde\x01\n\x0erpc_response_t\x12\x16\n\x0e\x63orrelation_id\x18\x01 \x01(\t\x12:\n\x06status\x18\x02 \x01(\x0e\x32*.swdv.dispatcher_rpc_envelope.rpc_status_t\x12\x13\n\x0bresult_json\x18\x03 \x01(\t\x12\x15\n\rerror_message\x18\x04 \x01(\t\x12\x13\n\x0b\x64uration_ms\x18\x05 \x01(\r\x12\x18\n\x10service_endpoint\x18\x06 \x01(\t\x12\x1d\n\x15response_timestamp_ms\x18\x07 \x01(\x12*\xa7\x01\n\x0crpc_status_t\x12\x0b\n\x07SUCCESS\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x12\x0b\n\x07TIMEOUT\x10\x02\x12\x17\n\x13SERVICE_UNAVAILABLE\x10\x03\x12\x14\n\x10METHOD_NOT_FOUND\x10\x04\x12\x16\n\x12INVALID_PARAMETERS\x10\x05\x12\x13\n\x0fTRANSPORT_ERROR\x10\x06\x12\x15\n\x11\x44UPLICATE_REQUEST\x10\x07\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dispatcher_rpc_envelope_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RPC_STATUS_T']._serialized_start=449
  _globals['_RPC_STATUS_T']._serialized_end=616
  _globals['_RPC_REQUEST_T']._serialized_start=64
  _globals['_RPC_REQUEST_T']._serialized_end=221
  _globals['_RPC_RESPONSE_T']._serialized_start=224
  _globals['_RPC_RESPONSE_T']._serialized_end=446
# @@protoc_insertion_point(module_scope)
